services:
  - type: web
    name: birducc-backend
    env: java
    plan: free
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/.jdk
